### ISSUE TITLE
Can't subscribe to topic

### ISSUE THREAD

**Issue by salimov7711** [becem-gharbi/nuxt-fcm#14]
Hello Cant subscribe to topic {
    "url": "/api/fcm/topic/subscribe",
    "statusCode": 401,
    "statusMessage": "",
    "message": "unauthorized",
    "stack": "<pre><span class=\"stack internal\">at handleError (D:\\V2\\node_modules\\@bg-dev\\nuxt-fcm\\dist\\runtime\\server\\utils\\error.mjs:7:19)</span>\n<span class=\"stack internal\">at Object.handler (D:\\V2\\node_modules\\@bg-dev\\nuxt-fcm\\dist\\runtime\\server\\api\\fcm\\topic\\subscribe.post.mjs:18:5)</span>\n<span class=\"stack internal\">at Object.handler (/D:/V2/node_modules/h3/dist/index.mjs:2196:34)</span>\n<span class=\"stack internal\">at /D:/V2/node_modules/h3/dist/index.mjs:1962:31</span>\n<span class=\"stack internal\">at async Object.callAsync (/D:/V2/node_modules/unctx/dist/index.mjs:72:16)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/D:/V2/node_modules/h3/dist/index.mjs:2249:7)</span></pre>"
}

**Comment by salimov7711** [comment]
Oh sorry ! I forgot to make a server middlware   to get access to topic methods. Everything works perfect now

**Comment by jochdev** [comment]
> Oh sorry ! I forgot to make a server middlware to get access to topic methods. Everything works perfect now

Could you share how you solved the problem?
