### ISSUE TITLE
Is it possible to handle notification click somewhere?

### ISSUE THREAD

**Issue by airDjura** [becem-gharbi/nuxt-fcm#16]
I need to send different kinds of notifications with specific actions on click. As far as I saw, only possible way to do it, is to register event listener in service worker.

```
self.addEventListener('notificationclick', function (event) {
    console.log("notificationclick", event)
    var urlToRedirect = event.notification.data.url;
    event.notification.close();
    event.waitUntil(self.clients.openWindow(urlToRedirect));
});
```

I'm not sure how can I do it using this module. Is there a way to override service worker somehow?

```
addServerHandler({
  route: "/firebase-messaging-sw.js",
  handler: resolve(runtimeDir, "server/routes/firebase-messaging-sw.get")
});
```

**Comment by becem-gharbi** [comment]
This is now possible. Please check [docs](https://github.com/becem-gharbi/nuxt-fcm?tab=readme-ov-file#listen-to-messages).
