### ISSUE TITLE
Duplicated notifications

### ISSUE THREAD

**Issue by airDjura** [becem-gharbi/nuxt-fcm#17]
I get the same notifications twice whenever I fire an event from BE.

I'm using SSR mode

I managed to make it work by deleting one part of the code from the file: `node_modules/@bg-dev/nuxt-fcm/dist/runtime/server/routes/firebase-messaging-sw.get.js`

```
messaging.onBackgroundMessage((payload) => {
      console.log("[firebase-messaging-sw.js] Received background message ", payload);

      self.registration.showNotification(
      payload.notification.title,
      payload.notification);
  });
```
I have no idea why, but it works normally without that line.

**Comment by becem-gharbi** [comment]
Apparently, background notifications are automatically shown. Thanks for the issue.

![image](https://github.com/user-attachments/assets/44010d39-6945-4c74-b966-0b65ac7e7586)
