### ISSUE TITLE
On Google Cloud Envirnoment Variables empty

### ISSUE THREAD

**Issue by Ombuweb** [becem-gharbi/nuxt-fcm#18]
Please help. I'm getting the error: "Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values)" when I deploy the app to Google Cloud. It seems that the Firebase config isn't being loaded from the environment in `defineNuxtConfig`

**Comment by becem-gharbi** [comment]
Hi, when loading `firebaseConfig` config object as env variable it should be parsed. This could be done either on build time via `nuxt.config` (check playground) or at runtime via matching env variables (recommended) [[docs](https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables)].

```.env
NUXT_PUBLIC_FCM_FIREBASE_CONFIG= {"apiKey": "___","authDomain": "__","projectId": "__","storageBucket": "___","messagingSenderId": "___","appId": "___"}
```
