### ISSUE TITLE
Unable to send Message

### ISSUE THREAD

**Issue by PMLS3** [becem-gharbi/nuxt-fcm#2]
Hi, thanks for the great repo..

I am having difficulty sending a message. 

I get the following 

![send](https://github.com/becem-gharbi/nuxt-fcm/assets/62140524/abfb45df-c5f6-4263-9554-f31c7b73d226)

This is working of the playground example

**Comment by becem-gharbi** [comment]
Can you provide the server logs and node version. And i wonder if this error is frequent ?

**Comment by PMLS3** [comment]
Node version 18.16.0
Not sure what server logs?
{"url":"/api/fcm/topic/send","statusCode":405,"statusMessage":"Method get is not allowed on this route.","message":"Method get is not allowed on this route.","stack":""}

**Comment by becem-gharbi** [comment]
The endpoint </api/fcm/topic/send> has `POST` method, thus `GET` is not allowed. Are you using `useFcmTopic` ?

**Comment by PMLS3** [comment]
I am yes, this is the text component: 

`<script setup lang="ts">

// import { ref, useFcmTopic, useFcm } from '#imports';

const message: any = ref("")
let registrationToken: any = ref(null)

const topic = ref("topic_2")

const { send, subscribe, unsubscribe } = useFcmTopic()

const { onMessage, getToken } = useFcm()

// console.log('token', await getToke)
onMounted(async ()=> {
if(process.client){
    registrationToken.value = await getToken()
console.log('reg', registrationToken.value)
}
})
 

onMessage((payload) => message.value = payload)

async function sendMessage() {
    console.log('topic', topic.value, registrationToken.value)
    send({
        topic:
            topic.value,
        payload: {
            notification: {
                title: "From client"
            },
            data: {
                "ok": "true"
            }
        },
        authorization: ''
    })
}


</script>
<template>
    <div>
        <h2>Registration token</h2>
        <p>{{ registrationToken }}</p>

        <h2 v-if="message">New message</h2>
        <p>{{ message }}</p>

        <button class="o_btn_primarys" @click="() => subscribe({ topic })">Subscribe</button>

        <button class="o_btn_primarys" @click="() => unsubscribe({ topic })">Unsubscribe</button>

        <button class="o_btn_primarys" @click="sendMessage">Send</button>

    </div>
</template>
  

  `

**Comment by becem-gharbi** [comment]
I'm not able to reproduce the issue, please make sure that `serviceAccount` is correct, Cloud Messaging API (Legacy) enabled, permissions are granted on middleware, firebase-admin on latest version.

**Comment by PMLS3** [comment]
Thanks for the feedback... it seems it might be the Cloud Messaging API (Legacy) : 

Cloud Messaging API (Legacy)Disabled
If you are newly integrating messaging into your app, use the latest Firebase Cloud Messaging API (V1). If you are an existing user of Cloud Messaging API (Legacy), consider migrating to the latest Firebase Cloud Messaging API (V1)

Are you planning to upgrade to latest versions seeing the Legacy might go unsupported in the future? 

Thanks for your time

**Comment by becem-gharbi** [comment]
Thanks for opening the issue,

The legacy API is meant for Legacy HTTP method, not for the SDK. By enabling Cloud Messaging API (Legacy) on firebase console, under the hood the `Cloud Messaging API` is enabled on GCP. This is required for SDK to work.

![image](https://github.com/becem-gharbi/nuxt-fcm/assets/99251251/c0757990-f5af-4be0-9b8b-78c1d5487751)
 
This setup is part of firebase-admin integration. I will add a note on README.

**Comment by PMLS3** [comment]
Thanks for your time and feedback on this
