### ISSUE TITLE
500 Service messaging isn't available

### ISSUE THREAD

**Issue by CruzedV** [becem-gharbi/nuxt-fcm#5]
Hi! I've got this strange issue, related with my firebaseConfig:

defineNuxtConfig: {
 ....
  ssr: true,
  fcm: {
      firebaseConfig: {
        apiKey: "XXXXXXXXXXX"",
        authDomain: "XXXXXXXXXXX"",
        databaseURL: "XXXXXXXXXXX"",
        projectId: "XXXXXXXXXXX"",
        storageBucket: "XXXXXXXXXXX"",
        messagingSenderId: "XXXXXXXXXXX",
        appId: "XXXXXXXXXXX",
        measurementId: "XXXXXXXXXXX"",
      },
      vapidKey: "XXXXXXXXXXX",
    },
  .....
}
But I ain't got this issue week before, 

![image](https://github.com/becem-gharbi/nuxt-fcm/assets/48482781/966b5a5b-50a7-4418-b0e6-ea3c0e572a60)

**Comment by becem-gharbi** [comment]
Hi,
This is weird that you got server error on a client plugin. Nevertheless, please make sure you to verify your firebase credentials and to add service worker.

**Comment by CruzedV** [comment]
My problem was in dependencies, I guess I accidentally deleted something important
