### ISSUE TITLE
Any way to pass firebaseConfig to firebase-messaging-sw.js?

### ISSUE THREAD

**Issue by Joey-Emery** [becem-gharbi/nuxt-fcm#6]
I really don't want to commit files into our git repo with configuration details in them, is there any way the SW JS file can use environment variables or have the configuration passed into it?

Thanks

**Comment by becem-gharbi** [comment]
Thanks very much for this brilliant idea, I just implemented it on [v0.2.7](https://github.com/becem-gharbi/nuxt-fcm/releases/tag/v0.2.7).

**Comment by Joey-Emery** [comment]
Man you work fast, that's insane thank you! 
I wrote a node script to put all the config in from the environment variables but your solution seems much slicker, really appreciate it
