### ISSUE TITLE
Is there any solution for exposed firebase data in client/browser ?

### ISSUE THREAD

**Issue by cax111** [becem-gharbi/nuxt-fcm#7]
Hi... I have a problem that when we add this module, our firebase data is exposed in client / browser source code. As I know that nuxt 3 expose the runtime config public data in the client side without separating the file or encrypt or anything that makes the data more secure. Which is the fcm data in this module I think has been moved to the runtimeConfig public when nuxt app running.
Can you give me an advice for that ?

Thanks.

**Comment by becem-gharbi** [comment]
Hi, the firebase configuration is meant to be accessed on client-side by the SDK. So there is no way to hide it and that's ok. You can read about this https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public.

What you can do is set security measures on production https://firebase.google.com/support/guides/launch-checklist
